In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import nltk
from nltk.corpus import stopwords
from nltk import word_tokenize, sent_tokenize
from nltk.stem import PorterStemmer
   
import string
import re
import warnings
warnings.filterwarnings("ignore")

In [2]:
path = r"C:\Users\DELL\Downloads\spam.csv"

In [3]:
df = pd.read_csv(path,encoding="latin1")

In [4]:
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [5]:
df.drop(columns=["Unnamed: 2","Unnamed: 3","Unnamed: 4"],inplace=True)

In [6]:
df.rename(columns={"v1":"Target","v2":"Msg"},inplace=True)

In [7]:
df.shape

(5572, 2)

In [8]:
x = df["Msg"][0]
print(x)

Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...

In [9]:
df.head()

  Target                                                Msg
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [14]:
df.msg = df.msg.str.lower()

In [16]:
df.head()

  target                                                msg
0    ham  go until jurong point, crazy.. available only ...
1    ham                      ok lar... joking wif u oni...
2   spam  free entry in 2 a wkly comp to win fa cup fina...
3    ham  u dun say so early hor... u c already then say...
4    ham  nah i don't think he goes to usf, he lives aro...

In [20]:
x = df.msg[0]

In [21]:
x

'go until jurong point, crazy.. available only in bugis n great world la e buffet... cine there got amore wat...'

In [26]:
lis = []
for i in word_tokenize(x):
    i = i.strip()
    if i not in string.punctuation:
        if i!=".." or i!="...":
            print(i)

go
until
jurong
point
crazy
..
available
only
in
bugis
n
great
world
la
e
buffet
...
cine
there
got
amore
wat
...

In [35]:
def syntax(x):
    lis = []
    p = string.punctuation
    w = stopwords.words("english")
    for i in word_tokenize(x):
        if (i not in p) and (i not in w):
            lis.append(i)
    return lis

In [36]:
syntax("We are learning NLP ?")

['We', 'learning', 'NLP']

In [39]:
df["msg2"] = df["msg"].apply(syntax)

In [40]:
df.head()

,target,msg,msg2
0,ham,"go until jurong point, crazy.. available only ...","[go, jurong, point, crazy, .., available, bugi..."
1,ham,ok lar... joking wif u oni...,"[ok, lar, ..., joking, wif, u, oni, ...]"
2,spam,free entry in 2 a wkly comp to win fa cup fina...,"[free, entry, 2, wkly, comp, win, fa, cup, fin..."
3,ham,u dun say so early hor... u c already then say...,"[u, dun, say, early, hor, ..., u, c, already, ..."
4,ham,"nah i don't think he goes to usf, he lives aro...","[nah, n't, think, goes, usf, lives, around, th..."

In [41]:
len(df["msg2"][0])

19

In [42]:
def length(x):
    return len(x)

In [43]:
df["Length"] = df["msg2"].apply(length)

In [44]:
df.head()

,target,msg,msg2,Length
0,ham,"go until jurong point, crazy.. available only ...","[go, jurong, point, crazy, .., available, bugi...",19
1,ham,ok lar... joking wif u oni...,"[ok, lar, ..., joking, wif, u, oni, ...]",8
2,spam,free entry in 2 a wkly comp to win fa cup fina...,"[free, entry, 2, wkly, comp, win, fa, cup, fin...",27
3,ham,u dun say so early hor... u c already then say...,"[u, dun, say, early, hor, ..., u, c, already, ...",11
4,ham,"nah i don't think he goes to usf, he lives aro...","[nah, n't, think, goes, usf, lives, around, th...",8

In [45]:
x = "We are learning NLP"

len(x)

19

In [59]:
def char(x):
    c = 0
    for i in x:
        if i.isalpha():
            c+=1
            return c

In [48]:
c = 0
c +=1
c

1

In [49]:
c+=1

In [50]:
c

2

In [57]:
df["characters"] = df["msg"].apply(char)

In [58]:
df.head()

,target,msg,msg2,Length,characters
0,ham,"go until jurong point, crazy.. available only ...","[go, jurong, point, crazy, .., available, bugi...",19,1.0
1,ham,ok lar... joking wif u oni...,"[ok, lar, ..., joking, wif, u, oni, ...]",8,1.0
2,spam,free entry in 2 a wkly comp to win fa cup fina...,"[free, entry, 2, wkly, comp, win, fa, cup, fin...",27,1.0
3,ham,u dun say so early hor... u c already then say...,"[u, dun, say, early, hor, ..., u, c, already, ...",11,1.0
4,ham,"nah i don't think he goes to usf, he lives aro...","[nah, n't, think, goes, usf, lives, around, th...",8,1.0